server:
  port: 7002

eureka:
  instance:
    hostname: service1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: acms

